title: Atelier Vélo Maxime
description: Réparation et entretien de vélos à Toulouse
theme: minima

header_pages:
  - prestations.md
  - tarifs.md
  - contact.md

author: Maxime
email: ton.email@example.com

# Pour inclure ton dossier CSS
include:
  - assets
