title: Atelier Vélo Maxime
description: Réparation et entretien de vélos à Toulouse
theme: minima

# Pages affichées dans le menu
header_pages:
  - prestations.md
  - tarifs.md
  - contact.md

author: Maxime
email: ton.email@example.com

# Lien vers ta feuille de style personnalisée
include:
  - assets
